apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: gavrielbereschit/user-service:latest   # Use your Docker Hub image
        ports:
        - containerPort: 3000                        # Ensure this matches your service's port
      imagePullSecrets:
      - name: regcred                                # Use the secret we created
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
  selector:
    app: user-service
